### PR TITLE
Task Provider Feature

### PR DESCRIPTION
**Pull request by elahehrashedi**
https://github.com/microsoft/vscode-cpptools/issues/3674 : Add support to run cpp build tasks (Tasks: Run Build Task)

Will also fix these bugs: 
https://github.com/microsoft/vscode-cpptools/issues/4278
https://github.com/microsoft/vscode-cpptools/issues/5285
https://github.com/microsoft/vscode-cpptools/issues/4278
https://github.com/microsoft/vscode-cpptools/issues/5270

Edited:
Refactoring the Task tools: **_Task: Configure Task_** and **_Task: Run Build Task_**, and **_C/C++: Build and Debug Active File_**
The multi-root is not implemented in this version yet. 
You have to use the insider Vs Code to test the proposed API for this feature (1.49.0-insider).

These are the behavior of the current version:

when **_Task: Run Build Task_** is called:
1. If there is a tasks.json file exists:
- >> if there is a default build task: the default build task will be run (no task will be shown to the user to choose from).
image
- >> if there is NO default task: The list of all defined tasks in tasks.json will be shown to the user to choose from.
image

2. If tasks.json file doesn't exist:
- >> the detected build tasks will be shown to the user to choose from. no tasks.json will be created.
image

P.S. right now only **_Task: Configure Task_** and **_C/C++: Build and Debug Active File_** can create a tasks.json file for the first time.

### CODE REVIEW

File: Extension/src/LanguageServer/cppbuildTaskProvider.ts [hunk 1]
```diff
@@ -0,0 +1,320 @@
...
+        }
+
+        const fileExt: string = path.extname(editor.document.fileName);
+        if (!fileExt) {
+            return [];
+        }
+
+        // Don't offer tasks for header files.
+        const fileExtLower: string = fileExt.toLowerCase();
+        const isHeader: boolean = !fileExt || [".hpp", ".hh", ".hxx", ".h", ".inl", ""].some(ext => fileExtLower === ext);
```
Comment (Colengms) [inline Extension/src/LanguageServer/cppbuildTaskProvider.ts]: I know you didn't write this part originally, but it looks like the native code (settings.h, line ~80-88) is also tracking ".h++", ".hp", ".i", ".ii", ".ino" and ".ipp" header extensions, and ".c++", ".cp", and ".tcc" source file extensions.  Could you add those here?   (It also associates ".idl" with C++, but idl isn't actually C++, so I'm not sure about that one.)

File: Extension/package.json [hunk 2]
```diff
@@ -40,9 +40,35 @@
   ],
   "activationEvents": [
     "*"
-  ],
+  ],
```
Comment (sean-mcmanus) [inline Extension/package.json]: extra space

File: Extension/src/LanguageServer/cppbuildTaskProvider.ts [hunk 3]
```diff
@@ -0,0 +1,320 @@
...
+        task.group = vscode.TaskGroup.Build;
+
+        return task;
+    };
+}
+
+class CustomBuildTaskTerminal implements vscode.Pseudoterminal {
+    private writeEmitter  = new vscode.EventEmitter<string>();
+    // eslint-disable-next-line no-invalid-this
+    onDidWrite: vscode.Event<string> = this.writeEmitter.event;
```
Comment (Colengms) [inline Extension/src/LanguageServer/cppbuildTaskProvider.ts]: Perhaps implement these are properties, so we don't have to disable lint errors for them?  i.e. public get onDidWrite(): vscode.Event<string> { return this.writeEmitter.event; }

File: Extension/package.json [hunk 4]
```diff
@@ -40,9 +40,35 @@
...
+  ], 
   "main": "./dist/main",
   "contributes": {
+    "taskDefinitions": [
+			{
+				"type": "cppbuild",
+				"required": [
+					"command"
+				],
+				"properties": {
```
Comment (sean-mcmanus) [inline Extension/package.json]: Can you format the doc? Seems like tabs are used.

File: Extension/package.json [hunk 5]
```diff
@@ -40,9 +40,35 @@
...
+						"type": "string",
+						"description": "The compiler path."
+					},
+					"args": {
+						"type": "array",
+						"description": "Additional build args."
+          },
+          "options": {
+            "type": "object",
+						"description": "Options {\"cwd\": cwd}."
```
Comment (sean-mcmanus) [inline Extension/package.json]: Does this need to go in an options object or can a "cwd" property be added directly?

File: Extension/package.nls.json [hunk 6]
```diff
@@ -18,7 +18,7 @@
...
-    "c_cpp.configuration.clang_format_style.description": "Coding style, currently supports: Visual Studio, LLVM, Google, Chromium, Mozilla, WebKit. Use \"file\" to load the style from a .clang-format file in the current or parent directory. Use {key: value, ...} to set specific parameters. For example, the \"Visual Studio\" style is similar to: { BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -4, NamespaceIndentation: All }",
+    "c_cpp.configuration.clang_format_style.description": "Coding style, currently supports: Visual Studio, LLVM, Google, Chromium, Mozilla, WebKit. Use \"file\" to load the style from a .clang-format file in the current or parent directory. Use {key: value, ...} to set specific parameters. For example, the \"Visual Studio\" style is similar to: { BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -4, NamespaceIndentation: All, Standard: Cpp03 }",
```
Comment (sean-mcmanus) [inline Extension/package.nls.json]: I don't think this change should be here. The Cpp03 is a special case and not the default.

File: Extension/src/Debugger/configurationProvider.ts [hunk 7]
```diff
@@ -7,7 +7,7 @@ import * as debugUtils from './utils';
 import * as os from 'os';
 import * as path from 'path';
 import * as vscode from 'vscode';
-import { getBuildTasks, BuildTaskDefinition } from '../LanguageServer/extension';
+import { CppBuildTaskProvider, CppBuildTaskDefinition} from '../LanguageServer/cppbuildTaskProvider';
```
Comment (sean-mcmanus) [inline Extension/src/Debugger/configurationProvider.ts]: cppBuildTaskProvider instead? Or is the cppbuildTaskProvider  casing intentional to match the cppbuild type?

File: Extension/package.json [hunk 8]
```diff
@@ -40,9 +40,35 @@
   ],
   "activationEvents": [
     "*"
-  ],
+  ], 
   "main": "./dist/main",
   "contributes": {
+    "taskDefinitions": [
+			{
+				"type": "cppbuild",
```
Comment (bobbrow) [inline Extension/package.json]: Can you format this file?  It should only have spaces in it, but I see TABs.

File: Extension/package.nls.json (hunk 6 above)
Comment (bobbrow) [inline Extension/package.nls.json]: This looks like it was meant to be part of one of your previous clang-format changes.  I think that commit was incorrectly added to this branch.

File: Extension/src/LanguageServer/cppbuildTaskProvider.ts [hunk 9]
```diff
@@ -0,0 +1,320 @@
...
+            return resolve({});
+        }
+        fs.exists(path, exists => {
+            if (!exists) {
+                return resolve({});
+            }
+            let fileContents: string = fs.readFileSync(path).toString();
+            fileContents = fileContents.replace(/^\s*\/\/.*$/gm, ""); // Remove start of line // comments.
+            let rawTasks: any = {};
+            try {
```
Comment (sean-mcmanus) [inline Extension/src/LanguageServer/cppbuildTaskProvider.ts]: Would it be easy to switch to jsonc.parse instead? colorization.ts uses that. That would enable the comment removal code to be omitted. We might have another issue tracking that.

**Review by sean-mcmanus — CHANGES_REQUESTED** [review]
I'm not finished reviewing...

File: Extension/src/LanguageServer/cppbuildTaskProvider.ts [hunk 10]
```diff
@@ -0,0 +1,320 @@
...
+
+export class CppBuildTaskProvider implements vscode.TaskProvider {
+    static CppBuildScriptType: string = 'cppbuild';
+    static CppBuildSourceStr: string = "C/C++";
+    private tasks: vscode.Task[] | undefined;
+
+    constructor() {}
+
+    public async provideTasks(): Promise<vscode.Task[]> {
+        if (this.tasks !== undefined) {
```
Comment (michelleangela) [inline Extension/src/LanguageServer/cppbuildTaskProvider.ts]: Can `if (this.tasks !== undefined)` be `if (this.tasks)` ? #Resolved

File: Extension/src/LanguageServer/cppbuildTaskProvider.ts [hunk 11]
```diff
@@ -0,0 +1,320 @@
...
+    }
+
+    // Resolves a task that has no [`execution`](#Task.execution) set.
+    public resolveTask(_task: vscode.Task): vscode.Task | undefined {
+        const execution: vscode.ProcessExecution | vscode.ShellExecution | vscode.CustomExecution | undefined = _task.execution;
+        if (execution === undefined) {
+            const definition: CppBuildTaskDefinition = <any>_task.definition;
+            return this.getTask(definition.command, false, false, definition.args ? definition.args : [], definition);
+        }
+        return undefined;
```
Comment (michelleangela) [inline Extension/src/LanguageServer/cppbuildTaskProvider.ts]: Just trying to understand what function does. Why does it return undefined if `(execution === undefined)` is false?

File: Extension/src/LanguageServer/extension.ts [hunk 12]
```diff
@@ -47,12 +47,10 @@ let realActivationOccurred: boolean = false;
 let tempCommands: vscode.Disposable[] = [];
 let activatedPreviously: PersistentWorkspaceState<boolean>;
 let buildInfoCache: BuildInfo | undefined;
-const taskTypeStr: string = "shell";
-const taskSourceStr: string = "C/C++";
 const cppInstallVsixStr: string = 'C/C++: Install vsix -- ';
 let taskProvider: vscode.Disposable;
 let codeActionProvider: vscode.Disposable;
-const intelliSenseDisabledError: string = "Do not activate the extension when IntelliSense is disabled.";
+export const intelliSenseDisabledError: string = "Do not activate the extension when IntelliSense is disabled.";
```
Comment (michelleangela) [inline Extension/src/LanguageServer/extension.ts:56]: Is this a user facing error that needs to be localized?

File: Extension/src/LanguageServer/cppbuildTaskProvider.ts [hunk 13]
```diff
@@ -0,0 +1,320 @@
...
+        }
+        const options: cp.ProcessEnvOptions | undefined = {"cwd": cwd};
+
+        // Double-quote the command if it is not already double-quoted.
+        let resolvedcompilerPath: string = isCl ? compilerPathBase : compilerPath;
+        if (resolvedcompilerPath && !resolvedcompilerPath.startsWith("\"") && resolvedcompilerPath.includes(" ")) {
+            resolvedcompilerPath = "\"" + resolvedcompilerPath + "\"";
+        }
+
+        if (definition === undefined) {
```
Comment (michelleangela) [inline Extension/src/LanguageServer/cppbuildTaskProvider.ts]: This can be `'if (!definition)`

**Comment by sean-mcmanus** [comment]
I'm seeing an issue when there are spaces in the ${file} path. I'm not able to get mingw or cl.exe to work. When the workspace folder is named "New folder", I get `cl : Command line warning D9024 : unrecognized source file type 'folder', object file assumed` . That scenario works with 0.28.3.

File: Extension/src/LanguageServer/cppbuildTaskProvider.ts [hunk 14]
```diff
@@ -0,0 +1,320 @@
...
+            this.tasks.push(this.getTask(userCompilerPath, returnCompilerPath, appendSourceToName, userCompilerPathAndArgs?.additionalArgs));
+        }
+
+        return this.tasks;
+    }
+
+    private getTask: (compilerPath: string, returnCompilerPath: boolean, appendSourceToName: boolean, compilerArgs?: string [], definition?: CppBuildTaskDefinition) => vscode.Task = (compilerPath: string, returnCompilerPath: boolean, appendSourceToName: boolean, compilerArgs?: string [], definition?: CppBuildTaskDefinition) => {
+
+        const filePath: string = path.join('${fileDirname}', '${fileBasenameNoExtension}');
+        const compilerPathBase: string = path.basename(compilerPath);
```
Comment (sean-mcmanus) [inline Extension/src/LanguageServer/cppbuildTaskProvider.ts]: extra blank line?

**Comment by sean-mcmanus** [comment]
Build errors are not reported:
```
Build finished with error:
        Command failed: 
```
I think we would need to implement our own problem matcher to report the errors and/or forward the results to the terminal?

**Comment by sean-mcmanus** [comment]
Also, I'm seeing unusual tab and newline behavior in the terminal output with cl.exe.

image

This is the 0.28.3 result:
Microsoft (R) C/C++ Optimizing Compiler Version 19.27.28919.3 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

test2.c
...\Test1\test2.c(5): error C2143: syntax error: missing ';' before '}'

File: Extension/src/LanguageServer/cppbuildTaskProvider.ts (hunk 1 above)
Comment (elahehrashedi) [reply Extension/src/LanguageServer/cppbuildTaskProvider.ts]: I modify the header and source file set as below:
["*.hpp", "*.hh", "*.hxx", "*.h++", "*.hp", "*.h", "*.ii", "*.ino", "*.inl", "*.idl", ""]
["*.cpp", "*.cc", "*.cxx", "*.c++", "*.cp", "*.ipp", "*.tcc"]

File: Extension/package.json (hunk 5 above)
Comment (elahehrashedi) [reply Extension/package.json]: there might be other properties added such as cwd, env, and shell.

File: Extension/src/LanguageServer/cppbuildTaskProvider.ts (hunk 11 above)
Comment (elahehrashedi) [reply Extension/src/LanguageServer/cppbuildTaskProvider.ts]: As far as I know, we can implement this function to return only undefined and the behaviour of the task feature won't change for now.
The tasks defined in tasks.json file pass-through this function to be resolved (the blanks are filled-out I guess).

File: Extension/src/LanguageServer/extension.ts (hunk 12 above)
Comment (elahehrashedi) [reply Extension/src/LanguageServer/extension.ts:56]: I am not sure. I had to use this error in cppBuildTaskProvider, so I exported it.

**Review by sean-mcmanus — CHANGES_REQUESTED** [review]
https://github.com/microsoft/vscode-cpptools/pull/5659#issuecomment-646374058
https://github.com/microsoft/vscode-cpptools/pull/5659#issuecomment-646385834
https://github.com/microsoft/vscode-cpptools/pull/5659#issuecomment-646387500

**Comment by elahehrashedi** [comment]
- A sample results of a compiler error (the file name includes Space as well):
image
image

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts [hunk 15]
```diff
@@ -0,0 +1,357 @@
...
+    private fileWatcher: vscode.FileSystemWatcher | undefined;
+
+
+    constructor(private command: string, private args: string[], private options: cp.ExecOptions | undefined, private workspaceRoot: string) {
+    }
+
+
+    open(_initialDimensions: vscode.TerminalDimensions | undefined): void {
+        telemetry.logLanguageServerEvent("cppBuildTaskStarted");
+        const pattern: string = path.join(this.workspaceRoot, 'cppBuild');
```
Comment (bobbrow) [inline Extension/src/LanguageServer/cppBuildTaskProvider.ts]: This file watcher stuff appears to be an artifact of the extension sample.  I think it can be safely removed.

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts [hunk 16]
```diff
@@ -0,0 +1,357 @@
...
+                    temp = "\"" + temp + "\"";
+                }
+                activeCommand = activeCommand + " " + temp;
+            });
+            if (this.options?.cwd) {
+                this.options.cwd = util.resolveVariables(this.options.cwd, this.AdditionalEnvironment);
+            }
+            cp.exec(activeCommand, this.options, (_error, stdout, _stderr) => {
+                if (_error) {
+                    telemetry.logLanguageServerEvent("cppBuildTaskError", { "error": _error.message });
```
Comment (bobbrow) [inline Extension/src/LanguageServer/cppBuildTaskProvider.ts]: I don't think we can safely log the "_error.message". This might have PII in it.  Let's just log the event name by itself instead.

File: Extension/package.json [hunk 17]
```diff
@@ -43,6 +43,33 @@
...
+            "type": "string",
+            "description": "Task's name."
+          },
+          "command": {
+            "type": "string",
+            "description": "The compiler path."
+          },
+          "args": {
+            "type": "array",
+            "description": "Additional build args."
```
Comment (michelleangela) [inline Extension/package.json]: >build [](start = 39, length = 5)

Are these args used for compiling? If so, describe as "Additional compiler args." ?

File: Extension/src/LanguageServer/extension.ts (hunk 12 above)
Comment (michelleangela) [reply Extension/src/LanguageServer/extension.ts:56]: I see that this error is thrown in function `realActivation()` and was never localized. May not be user facing then.

**Comment by michelleangela** [comment]
Are there any associated issues to this PR?

**Review by sean-mcmanus — APPROVED** [review]

File: Extension/package.json [hunk 18]
```diff
@@ -43,6 +43,33 @@
...
+      {
+        "type": "cppbuild",
+        "required": [
+          "command",
+          "label"
+        ],
+        "properties": {
+          "label": {
+            "type": "string",
+            "description": "Task's name."
```
Comment (bobbrow) [inline Extension/package.json]: We need to localize these

File: Extension/package.json (hunk 17 above)
Comment (michelleangela) [reply Extension/package.json]: What was the resolution to this question?

File: Extension/package.json (hunk 18 above)
Comment (bobbrow) [reply Extension/package.json]: Description texts:
`name` - "The name of the task."
`command` - "The path to either a compiler or script that performs compilation."
`args` - "Additional arguments to pass to the compiler or compilation script."

File: Extension/package.json [hunk 19]
```diff
@@ -43,6 +43,33 @@
...
+          },
+          "command": {
+            "type": "string",
+            "description": "The compiler path."
+          },
+          "args": {
+            "type": "array",
+            "description": "Additional compiler args."
+          },
+          "options": {
```
Comment (bobbrow) [inline Extension/package.json:65]: What is `options`?

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts [hunk 20]
```diff
@@ -0,0 +1,346 @@
...
+                    resolve(0);
+                }
+            });
+        }).finally (() => {
+            this.closeEmitter.fire(0);
+        });
+    }
+
+    private get AdditionalEnvironment(): { [key: string]: string | string[] } | undefined {
+
```
Comment (bobbrow) [inline Extension/src/LanguageServer/cppBuildTaskProvider.ts]: remove empty newline

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts [hunk 21]
```diff
@@ -0,0 +1,346 @@
...
+class CustomBuildTaskTerminal implements vscode.Pseudoterminal {
+    private writeEmitter  = new vscode.EventEmitter<string>();
+    private closeEmitter = new vscode.EventEmitter<number>();
+    public get onDidWrite(): vscode.Event<string> { return this.writeEmitter.event; }
+    public get onDidClose(): vscode.Event<number> { return this.closeEmitter.event; }
+
+    constructor(private command: string, private args: string[], private options: cp.ExecOptions | undefined) {
+    }
+
```
Comment (bobbrow) [inline Extension/src/LanguageServer/cppBuildTaskProvider.ts:303]: remove 1 empty newline here

File: Extension/package.json (hunk 19 above)
Comment (elahehrashedi) [reply Extension/package.json:65]: some build options like "cwd" and "env" goes to this part.

File: Extension/package.json [hunk 22]
```diff
@@ -43,6 +43,33 @@
...
+          "label"
+        ],
+        "properties": {
+          "label": {
+            "type": "string",
+            "description": "Task's name."
+          },
+          "command": {
+            "type": "string",
+            "description": "The compiler path."
```
Comment (Colengms) [inline Extension/package.json]: Elsewhere in pacakge.json, you will see settings, etc., that have `description` fields containing `%`'s.  i.e. `"description": "%c_cpp.configuration.clang_format_style.description%"`.  These refer to localized strings, with the English version of the string specified in package.nls.json.  I believe you can localize these descriptions using the same approach.

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts [hunk 23]
```diff
@@ -0,0 +1,346 @@
...
+        // At this point we can start using the terminal.
+        this.writeEmitter.fire("Starting build...\r\n");
+        this.doBuild();
+    }
+
+    close(): void {
+        // The terminal has been closed. Shutdown the build.
+    }
+
+    private async doBuild(): Promise<number> {
```
Comment (Colengms) [inline Extension/src/LanguageServer/cppBuildTaskProvider.ts]: Since this function does not 'await' any other functions, I don't believe it needs to be declared as `async`.  There is also a `execChildProcess` in common.ts which converts `exec` into an await-able function.  You could either a) remove the `await`, or b) await `execChildProcess` instead of invoking `exec` directly.  B seems better, as you could avoid creating a new Promise object directly, and use `try`/`catch`.

Also, where `doBuild` is called, the Promise you are returning is not awaited.  Is the intention to complete the `exec` before `open` returns?  If so, you'll want to await the result of doBuild.  Or, if not, doBuild() doesn't need to return a promise at all or be async.

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts [hunk 24]
```diff
@@ -0,0 +1,346 @@
...
+        const file: string = editor.document.fileName;
+        return {
+            "file": file,
+            "fileDirname": fileDir.uri.fsPath,
+            "fileBasenameNoExtension": path.parse(file).name,
+            "workspaceFolder": fileDir.uri.fsPath};
+    }
+}
+
+export function getRawTasksJson(): Promise<any> {
```
Comment (Colengms) [inline Extension/src/LanguageServer/cppBuildTaskProvider.ts]: I know you didn't write this function, but...  There is a `checkFileExists` function in common.ts that is await-able.  If that was used instead, this function could be made await-able and simplified.

**Review by Colengms — CHANGES_REQUESTED** [review]

File: Extension/package.json (hunk 22 above)
Comment (elahehrashedi) [reply Extension/package.json]: It's updated in the new branch.

File: Extension/package.json (hunk 19 above)
Comment (elahehrashedi) [reply Extension/package.json:65]: what would be a good description for it? 
"c_cpp.taskDefinitions.options.description": "Additional options including cwd and env."

Comment (bobbrow) [reply Extension/package.json:65]: If there are additional properties supported in here, you need to list them out.  I believe you use `"properties": { }`

Reply: in shell tasks, it was called "options", and in vscode, the interface is named execoptions,  that's why I kept that same name.

File: Extension/CHANGELOG.md [hunk 25]
```diff
@@ -1,35 +1,24 @@
 # C/C++ for Visual Studio Code Change Log
 
-## Version 0.29.0-insiders2: July 8, 2020
+## Version 0.29.0: July 15, 2020
 ### New Features
-* Added support for LogMessage Breakpoints for debug type `cppdbg`. [#1013](https://github.com/microsoft/MIEngine/pull/1013)
-* Switch to using the VS Code Semantic Tokens API for semantic colorization. [PR #5401](https://github.com/microsoft/vscode-cpptools/pull/5401)
+* Add Doxygen comment support (to tooltip display of hover, completion, and signature help). [#658](https://github.com/microsoft/vscode-cpptools/issues/658)
+  * Add `C_Cpp.simplifyStructuredComments` setting. [#5706](https://github.com/microsoft/vscode-cpptools/issues/5706)
```
Comment (bobbrow) [inline Extension/CHANGELOG.md]: The link to the issue on this sub bullet is not needed because it's part of the parent feature and was addressed as part of the insiders.
You can just mention "The way comments are formatted is controlled by the `C_Cpp.simplifyStructuredComments` setting."

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts [hunk 26]
```diff
@@ -0,0 +1,346 @@
...
+        const fileDir: vscode.WorkspaceFolder | undefined = vscode.workspace.getWorkspaceFolder(editor.document.uri);
+        if (!fileDir) {
+            return undefined;
+        }
+        const file: string = editor.document.fileName;
+        return {
+            "file": file,
+            "fileDirname": fileDir.uri.fsPath,
+            "fileBasenameNoExtension": path.parse(file).name,
+            "workspaceFolder": fileDir.uri.fsPath};
```
Comment (bobbrow) [inline Extension/src/LanguageServer/cppBuildTaskProvider.ts]: nit: the closing curly brace should be on a new line

Comment (elahehrashedi) [reply Extension/src/LanguageServer/cppBuildTaskProvider.ts]: I format the whole file.

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts (hunk 23 above)
Comment (elahehrashedi) [reply Extension/src/LanguageServer/cppBuildTaskProvider.ts]: I added an await on the `exec` directly. It was a good idea to re-use `execChildProcess` instead, but it had a `vscode.OutputChannel` as input, so I couldn't re-use it. 
yes, we want to wait for `exec` to complete before `open` returns. I added `await` to the result of `dobuild` as well.

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts (hunk 24 above)
Comment (elahehrashedi) [reply Extension/src/LanguageServer/cppBuildTaskProvider.ts]: `getRawTasksJson` is modified now.

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts [hunk 27]
```diff
@@ -0,0 +1,342 @@
...
+            let temp: string = util.resolveVariables(value, this.AdditionalEnvironment);
+            if (temp && temp.includes(" ")) {
+                temp = "\"" + temp + "\"";
+            }
+            activeCommand = activeCommand + " " + temp;
+        });
+        if (this.options?.cwd) {
+            this.options.cwd = util.resolveVariables(this.options.cwd, this.AdditionalEnvironment);
+        }
+        await new Promise<number>((resolve, reject) => {
```
Comment (bobbrow) [inline Extension/src/LanguageServer/cppBuildTaskProvider.ts]: If you await something that will potentially `reject` the promise, you should wrap it with `try/finally`.  Though it probably makes more sense to resolve to -1 than to reject the promise.  Give this a try:
```
        try {
            const result = await new Promise<number>((resolve, reject) => {
                cp.exec(activeCommand, this.options, (_error, stdout, _stderr) => {
                    if (_error) {
                        telemetry.logLanguageServerEvent("cppBuildTaskError");
                        this.writeEmitter.fire("Build finished with error:\r\n");
                        this.writeEmitter.fire(stdout.toString());
                        resolve(-1);
                    } else {
                        this.writeEmitter.fire(stdout.toString());
                        this.writeEmitter.fire("\r\nBuild finished successfully.\r\n");
                        resolve(0);
                    }
                });
            });
            this.closeEmitter.fire(result);
        } catch {
            this.closeEmitter.fire(-1);
        }
```

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts (hunk 23 above)
Comment (Colengms) [reply Extension/src/LanguageServer/cppBuildTaskProvider.ts]: The question mark in `channel?: vscode.OutputChannel` indicates the channel param is optional.

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts (hunk 24 above)
Comment (Colengms) [reply Extension/src/LanguageServer/cppBuildTaskProvider.ts]: I was hoping we could remove creation of a new promise here, as it's not necessary if this function is async, and calls await on checkFileExists (instead of then()).  This function could be very simple:
```
export async function getRawTasksJson(): Promise<any> {
    const path: string | undefined = getTasksJsonPath();
    if (!path) {
        return {};
    }
    const fileExists: boolean = await util.checkFileExists(path);
    if (!fileExists) {
        return {};
    }

    const fileContents: string = await util.readFileText(path);
    let rawTasks: any = {};
    try {
        rawTasks = jsonc.parse(fileContents);
    } catch (error) {
        throw new Error(failedToParseTasksJson);
    }
    return rawTasks;
}
```

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts (hunk 27 above)
Comment (elahehrashedi) [reply Extension/src/LanguageServer/cppBuildTaskProvider.ts]:
```
        try {
            await new Promise<number>((resolve, reject) => {
                cp.exec(activeCommand, this.options, (_error, stdout, _stderr) => {
                    if (_error) {
                        telemetry.logLanguageServerEvent("cppBuildTaskError");
                        const endOfLine: string = stdout ? ":" : ".";
                        this.writeEmitter.fire("Build finished with error" + endOfLine + "\r\n");
                        this.writeEmitter.fire(stdout.toString());
                        resolve(-1);
                    } else {
                        this.writeEmitter.fire(stdout.toString());
                        this.writeEmitter.fire("\r\nBuild finished successfully.\r\n");
                        resolve(0);
                    }
                });
            });
            this.closeEmitter.fire(0);
        } catch {
            this.closeEmitter.fire(-1);
        }
```

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts (hunk 23 above)
Comment (elahehrashedi) [reply Extension/src/LanguageServer/cppBuildTaskProvider.ts]: I need to print the stdout (instead of error message) in the case that exec finishes with error.

File: Extension/CHANGELOG.md [hunk 28]
```diff
@@ -18,6 +18,7 @@
 * Add `quoteArgs` to `launch.json` schema. [PR #5639](https://github.com/microsoft/vscode-cpptools/pull/5639)
 * Add logs for a resolved `launch.json` if "engineLogging" is enabled. [PR #5644](https://github.com/microsoft/vscode-cpptools/pull/5644)
 * Add threadExit and processExit logging flags for 'cppvsdbg'. [PR #5652](https://github.com/microsoft/vscode-cpptools/pull/5652)
+* Add support to run cpp build tasks  (Tasks: Run Build Task) [#3674](https://github.com/microsoft/vscode-cpptools/issues/3674)
```
Comment (sean-mcmanus) [inline Extension/CHANGELOG.md]: This is moved to a 0.30.0-insiders changelog...we could update the changelog in a separate PR, since it's still in flux.

File: Extension/src/LanguageServer/cppBuildTaskProvider.ts (hunk 23 above)
Comment (Colengms) [reply Extension/src/LanguageServer/cppBuildTaskProvider.ts]: It could be updated to return that also.  :)  Generally, I'm suggesting that creation of Promises are pushed down into helper functions, as async/await syntax is so much easier to read and understand.  Not critical, though.

File: Extension/package.json [hunk 29]
```diff
@@ -7,6 +7,7 @@
   "preview": true,
   "icon": "LanguageCCPP_color_128x.png",
   "readme": "README.md",
+  "enableProposedApi": true,
```
Comment (bobbrow) [inline Extension/package.json]: We can't check in this line

**Review by michelleangela — APPROVED** [review]

**Review by Colengms — APPROVED** [review]

File: Extension/package.nls.json [hunk 30]
```diff
@@ -220,10 +220,10 @@
     "c_cpp.debuggers.symbolLoadInfo.loadAll.description": "If true, symbols for all libs will be loaded, otherwise no solib symbols will be loaded. Default value is true.",
     "c_cpp.debuggers.symbolLoadInfo.exceptionList.description": "List of filenames (wildcards allowed) separated by semicolons ';'. Modifies behavior of LoadAll. If LoadAll is true then don't load symbols for libs that match any name in the list. Otherwise only load symbols for libs that match. Example: \"foo.so;bar.so\"",
     "c_cpp.debuggers.requireExactSource.description": "Optional flag to require current source code to match the pdb.",
-    "c_cpp.taskDefinitions.name.description": "The name of the task.",
-    "c_cpp.taskDefinitions.command.description": "The path to either a compiler or script that performs compilation.",
-    "c_cpp.taskDefinitions.args.description": "Additional arguments to pass to the compiler or compilation script.",
-    "c_cpp.taskDefinitions.options.description": "Additional command options.",
+    "c_cpp.taskDefinitions.name.description": "The name of the task",
```
Comment (bobbrow) [inline Extension/package.nls.json:223]: Should these periods have remained?
