### ISSUE TITLE
cpptools 0.11.0 stopped working after update

### ISSUE THREAD

**Issue by UR3IQO** [microsoft/vscode-cpptools#667]
After update from the 0.10.5 to 0.11.0, cpptools do not work at all, the debug console indicates the following error:
```
[Extension Host] rejected promise not handled within 1 second
Cannot read property 'name' of undefined: TypeError: Cannot read property 'name' of undefined
    at ConfigurationProperties.UpdateStatusBar (C:\Users\Олег\.vscode\extensions\ms-vscode.cpptools-0.11.0\out\src\LanguageServer\C_Cpp_ConfigurationProperties.js:92:127)
    at new ConfigurationProperties (C:\Users\Олег\.vscode\extensions\ms-vscode.cpptools-0.11.0\out\src\LanguageServer\C_Cpp_ConfigurationProperties.js:177:18)
    at Object.setupConfigurationProperties (C:\Users\Олег\.vscode\extensions\ms-vscode.cpptools-0.11.0\out\src\LanguageServer\C_Cpp_ConfigurationProperties.js:401:15)
    at Object.activate (C:\Users\Олег\.vscode\extensions\ms-vscode.cpptools-0.11.0\out\src\LanguageServer\C_Cpp.js:86:62)
    at processRuntimeDependencies (C:\Users\Олег\.vscode\extensions\ms-vscode.cpptools-0.11.0\out\src\main.js:39:15)
    at util.checkLockFile.then (C:\Users\Олег\.vscode\extensions\ms-vscode.cpptools-0.11.0\out\src\main.js:147:13)
```
Everything starts working after rollback to 0.10.5

**Comment by sean-mcmanus** [comment]
That is strange. You can view/modify the javascript at the location shown to try to resolve the issue. Adding code `if (this.configurationJson.configurations[this.currentConfigurationIndex] == undefined) return;` would fix the error, but the condition should never happen, so there's probably something else going wrong. I think we'll need to somehow get a repro. Can you try deleting your c_cpp_properties.json and do another Edit Configuration? We've updated it so it's possible the changes you made were incompatible with the new schema.

**Comment by sean-mcmanus** [comment]
I can get the bug to repro by deleting the "name" element of the config in c_cpp_properties.json -- can you make sure the name is there?

**Comment by UR3IQO** [comment]
Thanks for the reply! Yes, it is there, but I found the problem. I use vscode for the cross development (mainly for the ARM MCUs) and set name to 'ARM' - I though that the name can be freely selected and simply indicates current config for the user. Changing name to 'Win32' solved the problem, but such a limitation is not a good thing.

**Comment by sean-mcmanus** [comment]
Ah, thanks for the repro details. Yeah, changing the Win32 config name to ARM is actually supposed to work. It seems like this is a regression, maybe from the code we added to auto-populate the platform-specific SDK paths.

**Comment by bobbrow** [comment]
I know what's wrong here.  The extension currently expects there to be at least 3 configs present in the file and one of them is expected to match the OS identifier.  The old code would pick the last config in the file if nothing matched the OS identifier.  The new code has a path that doesn't actually end up picking any config if you have <= 3 configs and none of them match the OS identifier.  It's a pretty easy fix.

If you edit `C:\Users\Олег\.vscode\extensions\ms-vscode.cpptools-0.11.0\out\src\LanguageServer\C_Cpp_ConfigurationProperties.js` by adding `return this.configurationJson.configurations.length - 1;` on line 122, you should be able to rename your Win32 config to ARM again.

Another workaround would be to add a copy of the "Win32" config and rename it to "ARM" (so that you have 4 configs in the JSON file).  The extension will default to selecting that 4th config every time.

**Comment by UR3IQO** [comment]
Thanks! Adding line 122 completely solved the problem.

**Comment by bobbrow** [comment]
This is fixed in 0.11.1
