### ISSUE TITLE
IntelliSense, Code Formatting not Working on Remote After VS Code 1.53 Update

### ISSUE THREAD

**Issue by malithj** [microsoft/vscode-cpptools#6936]
**Type: LanguageService**

LanguageService seems to be having issues in remote environments after an update to VS Code. In a local environment, the plugin works fine with no issues.

**Describe the bug**
- OS and Version: macOS Mojave (version: 10.14.6)
- VS Code Version: 1.53
- C/C++ Extension Version: 1.2.0
- Other extensions you installed (and if the issue persists after disabling them): Issue persists
- Does this issue involve using SSH remote to run the extension on a remote machine?: Yes
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
When connecting to a remote environment from VS Code start page, an error occurs and stops the plugin from loading. 

**Steps to reproduce**

1. Go to VS Code start page.
2. Click on ```Remote-ssh: Connect to Host```
3. Toggle Developer Tools (```Help -> Toggle Developer Tools```)

```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60
[Extension Host] 
(node:3683) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

abstractExtensionService.ts:718 Activating extension 'ms-vscode.cpptools' failed: Cannot find module '/home/[user]/.vscode-server/extensions/ms-vscode.cpptools-1.2.0/dist/main'
Require stack:
- /home/[user]/.vscode-server/bin/8490d3dde47c57ba65ec40dd192d014fd2113496/out/vs/loader.js
- /home/[user]/.vscode-server/bin/8490d3dde47c57ba65ec40dd192d014fd2113496/out/bootstrap-amd.js
- /home/[user]/.vscode-server/bin/8490d3dde47c57ba65ec40dd192d014fd2113496/out/bootstrap-fork.js.

```

**Expected behavior**

Loading cpptools successfully on remote server.

<details>
  <summary><strong>Logs</strong></summary>

```
N/A
```
</details>

**Screenshots**

<img width="812" alt="Screen Shot 2021-02-09 at 11 20 59 AM" src="https://user-images.githubusercontent.com/16982827/107394009-66c3a280-6ac9-11eb-8981-cc5c2f217d85.png">

**Additional context**

**Comment by AngleWing** [comment]
Having the same issue. Please help.

**Comment by Eric-Frank-Ver** [comment]
Reproduced on OSX 10.15 with VSCode version 1.53.1. Seeing Intellisense fail to open include statements in C and C/C++ formatter on save call seems to be hanging.

**Comment by sean-mcmanus** [comment]
This sounds like a bug with the Remote-SSH extension and/or VS Code itself and not a bug with our extension. Could you file a bug at https://github.com/microsoft/vscode-remote-release/issues ?

i.e. it sounds like the issue started when you updated to VS Code 1.53 and the issue would still repro if you installed an older version of our C/C++ extension (which last updated a week ago).

**Comment by AngleWing** [comment]
In my case, it's not only remote-ssh. After opening a workspace for a while, the cpp intellisence would stop working and cannot find the definition/declaration or render the scope folding control. No update found. Same deprecation error

**Comment by Colengms** [comment]
Hi @malithj , @AngleWing , @Eric-Frank-Ver .  If you are seeing a "Cannot find module" error, it's possible an error occurred when installing/upgrading the extension.  I had opened this issue against VS Code for previous occurrences of this: https://github.com/microsoft/vscode/issues/100537

Could you take a look at that issue, and set aside the vsix they are asking for?  Then, could you try deleting the entire ms-vscode.cpptools-x.x.x folder from the extensions folder and reinstalling the extension?  If the newly installed version works, perhaps we could get VS Code to revisit that issue.

**Comment by malithj** [comment]
@sean-mcmanus Thank you for replying. I tried cpptools version `1.1.3` and the plugin works as expected with VS Code 1.53. For now, as a work around, I've disabled auto-plugin updates and down graded cpptools to version `1.1.3`.

@Colengms I tried uninstalling using the command line (with vsix). I also deleted the extension folder (`ms-vscode.cpptools-1.2.0`) from `~/.vscode/extensions` and then reinstalled the plugin. However, the issue persists.

**Comment by Colengms** [comment]
@malithj , did you mean that you removed it from the `~/.vscode-server/extensions` folder?  It would need to be removed from the remote machine.  Also, could you provide the platform and architecture of the remote machine?

**Comment by malithj** [comment]
@Colengms Sorry my mistake. I previously deleted the local directory. I deleted the remote extensions directory and reinstalled the plugin. Everything's working now. 😃 

Remote is running Ubuntu 18.04.3 LTS (linux kernel: 5.4.0-60-generic). 
Architecture is x86_64: Intel(R) Core(TM) i9-9920X

**Comment by Colengms** [comment]
@malithj Thanks for confirming.  It sounds like the issue has to do with VS Code itself failing to install our extension.  I've not gotten much traction on this issue yet, so I'd encourage anyone who encounters it to also open an issue in the [VS Code repo](https://github.com/microsoft/vscode).

Since your repro is addressed, I'll close this issue.  @AngleWing , @Eric-Frank-Ver If the info here does not also address what you're seeing, please open new issues.

**Comment by AngleWing** [comment]
@Colengms, the issue for me is solved by not installing 1.2.0. Downgrade to 1.1.3 solved all the problem. So I think it's still a bug in 1.2.0 extension.
