### ISSUE TITLE
Identical Struct Tags and Definitions

### ISSUE THREAD

**Issue by savtachayameta** [microsoft/vscode-cpptools#1290]
>**OS**: Ubuntu 17.04 x64
**VS Code**: 
Version 1.18.1
Commit 929bacba01ef658b873545e26034d1a8067445e9
Date 2017-11-16T18:34:22.110Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
**C/C++ Extension**: Version 0.14.3

Hi,
The following code snippet uses identical struct tags and definitions.
When going to definition of `struct s1`, I get multiple definitions even though there is only one.
```
struct s1 {
};

struct s2 {
	struct s1 s1;
};

struct s3 {
	struct s1 s1;
};

struct s1 s1;
```

Screenshot:
![vscode](https://user-images.githubusercontent.com/34054830/33307334-cbcf07e0-d41e-11e7-80c8-41ac4d41b850.png)

Is there a way to get the only real definition (the first one)?

I'm using `"C_Cpp.intelliSenseEngine": "Default"`

Thanks!

**Comment by bobbrow** [comment]
Code navigation is still implemented using the Tag Parser, so that would explain why you see so many duplicates.  Issue #255 is being used to track the implementation of code browsing using the Default IntelliSense engine.

**Comment by sean-mcmanus** [comment]
Go to Definition on the "s1" in "struct s1" works with 0.19.0, but when done on the last s1 in "struct s1 s1;" it falls back to the old behavior -- I'm tracking that with https://github.com/Microsoft/vscode-cpptools/issues/2573 . Go to Def of the s1 global variable in the current file works correctly, just not on the identifier name in the definition itself (UPDATE: Fixed with https://github.com/Microsoft/vscode-cpptools/releases/tag/0.19.1-insiders ).
