### ISSUE TITLE
ms-vscode.cpptools-0.25.0-insiders2 fails to run on Mac OS 10.12

### ISSUE THREAD

**Issue by xiujiecn** [microsoft/vscode-cpptools#4096]
Type: Debugger

**Describe the bug**
- OS and Version:10.12.5 (16F73)
- VS Code Version:1.37.1
- C/C++ Extension Version:0.25.0-insiders2

**Error**
```
dyld: Symbol not found: __ZTISt18bad_variant_access
  Referenced from: /Users/lixiujie/.vscode/extensions/ms-vscode.cpptools-0.25.0-insiders2/bin/Microsoft.VSCode.CPP.Extension.darwin
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/lixiujie/.vscode/extensions/ms-vscode.cpptools-0.25.0-insiders2/bin/Microsoft.VSCode.CPP.Extension.darwin
[Error - 11:45:45 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by sean-mcmanus** [comment]
Looks like Mac 10.12 doesn't support calling C++17 std::visit due to bad_variant_access being undefined: https://stackoverflow.com/questions/52310835/xcode-10-call-to-unavailable-function-stdvisit .

Looks like we'd need to re-write our code to not use std::visit (or some other fix). Until then, the workaround would be to use 0.25.0-insiders or 0.24.1 or upgrade your Mac to 10.14.

**Comment by navyxliu** [comment]
Thanks! I can confirm that '0.25.0-insiders' works on Macos 10.12. 

I don't have a brave heart. Is it possible to tell vcode doesn't update preview or insiders revision for me?  I'd like to stay on stable version.

**Comment by sean-mcmanus** [comment]
@navyxliu You can set C_Cpp.updateChannel to "Default" to avoid getting updated to our latest "insider" vsix's.

**Comment by nygymankussainov** [comment]
I confirm that I have MacOS 10.12.6 version and I have this problem **The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.**

**Comment by csujedihy** [comment]
I am seeing the same problem on Windows.

 The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by sean-mcmanus** [comment]
@csujedihy That is the same symptom with a different root cause. Is this with the 0.25.0-insiders2 or 0.24.1? Can you attach a debugger to the Microsoft.VSCode.CPP.Extension.exe before the crash to get a call stack? If it crashes too early to attach, you could try simplifying the workspace to avoid the crash and then add back in the stuff that makes it crash?

**Comment by sean-mcmanus** [comment]
The Mac 10.12 incompatibility issue is fixed with 0.25.0.
